services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Madrid

    volumes:
      - /var/lib/docker/duplicati:/config
      - /var/lib/docker/duplicati/:/backups
      - /var/lib/docker/duplicati:/source
    ports:
      - 8200:8200
    restart: unless-stopped
